"""add chatflow as tool conversations

Revision ID: 3b6551091d65
Revises: ea003902b54e
Create Date: 2024-12-07 11:52:42.685848

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6551091d65'
down_revision = 'ea003902b54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatflow_tool_conversations',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_conversation_id', models.types.StringUUID(), nullable=False),
    sa.Column('chatflow_id', models.types.StringUUID(), nullable=False),
    sa.Column('chatflow_conversation_id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='chatflow_tool_conversations_pkey')
    )
    with op.batch_alter_table('chatflow_tool_conversations', schema=None) as batch_op:
        batch_op.create_index('app_conversation_id_idx', ['app_conversation_id', 'chatflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatflow_tool_conversations', schema=None) as batch_op:
        batch_op.drop_index('app_conversation_id_idx')

    op.drop_table('chatflow_tool_conversations')
    # ### end Alembic commands ###
