"""add state_tool_conv_states table

Revision ID: 418bb48a90be
Revises: 84412a900464
Create Date: 2024-08-01 10:52:50.330168

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '418bb48a90be'
down_revision = '84412a900464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_tool_conv_states',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('conversation_id', models.StringUUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='stcs_pkey')
    )
    with op.batch_alter_table('state_tool_conv_states', schema=None) as batch_op:
        batch_op.create_index('stcs_conversation_id_idx', ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('state_tool_conv_states', schema=None) as batch_op:
        batch_op.drop_index('stcs_conversation_id_idx')

    op.drop_table('state_tool_conv_states')
    # ### end Alembic commands ###
