"""add table workflow_running_collects

Revision ID: 84412a900464
Revises: eeb2e349e6ac
Create Date: 2024-08-01 09:45:57.777413

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '84412a900464'
down_revision = 'eeb2e349e6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_running_collects',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.StringUUID(), nullable=False),
    sa.Column('app_id', models.StringUUID(), nullable=False),
    sa.Column('workflow_id', models.StringUUID(), nullable=False),
    sa.Column('workflow_version', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('collect_node_id', sa.String(length=255), nullable=False),
    sa.Column('current_runs', sa.Integer(), nullable=False),
    sa.Column('created_from', sa.String(length=255), nullable=False),
    sa.Column('variable_dict', sa.Text(), nullable=True),
    sa.Column('created_by', models.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='workflow_running_collect_pkey')
    )
    with op.batch_alter_table('workflow_running_collects', schema=None) as batch_op:
        batch_op.create_index('workflow_running_collect_conv_idx', ['tenant_id', 'app_id', 'workflow_id', 'workflow_version', 'conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('workflow_running_collects', schema=None) as batch_op:
        batch_op.drop_index('workflow_running_collect_conv_idx')

    op.drop_table('workflow_running_collects')
    # ### end Alembic commands ###
